In [1]:
#Import Libraries

import pandas as pd

In [2]:
#Load Data set

df = pd.read_csv("social_media_interactions_contaminated.csv")

In [3]:
#Check dataset

df

,CustomerID,InteractionID,InteractionDate,Platform,InteractionType,Sentiment
0,2dcb9523-356b-40b2-a67b-1f27797de261,e5d15761-d0a7-4329-89e3-79a892c56097,2023-07-11,NaN,Comment,NaN
1,e12c37b3-7d4d-472f-9fd8-0df2cb3001aa,02f9f376-70ae-4fcd-9070-1db977939948,2023-07-06,Twitter,Share,NaN
2,08a911a3-65e6-4f5d-a6a1-ae7ddcbe28a2,a83fa04c-f109-4f24-8ce1-2078154f6a1c,2024-05-24,Instagram,Comment,Neutral
3,efdfdfc9-5dbb-4478-911a-101a390a0285,28a69c4b-a2e4-4c74-a130-1132d7733fdf,2023-11-01,Instagram,Like,Neutral
4,ca1e90f6-0e5f-492e-ab92-252ff540da18,d9d1c6f8-5e15-4738-b52b-13c2982420cc,2023-07-08,Instagram,Like,NaN
...,...,...,...,...,...,...
3195,8d8fe8bd-2009-4a15-be37-83dba3cef447,2212803c-4a00-4263-bae5-aaaff6d6bdb1,2023-08-30,Instagram,Like,Neutral
3196,1756838b-8368-4852-b4a5-32a23643a3dd,2f50ca57-f930-4d3e-ae08-9f3b26c7f148,2024-06-16,Facebook,Like,Neutral
3197,eb8bb3ce-e182-4a9c-8084-c55c738815e1,ee2c3d14-248c-48b0-aa80-4ea97e449bf8,2023-12-22,Instagram,Comment,Negative
3198,a5d08a95-9dba-4e3d-b997-1cfdde6a89ef,e77a8713-fdc7-4f71-85f8-9cd88cca0c42,2023-11-01,Twitter,Share,Positive
3199,f8146100-569d-4cda-9d64-88c6ad98de5f,454a0b90-d1bb-437d-ad50-ef01821fbf0a,2024-06-20,Instagram,Like,Neutral

In [4]:
#Checking Dataset info (Shape, Dtype)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3200 entries, 0 to 3199
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       3200 non-null   str
 1   InteractionID    3200 non-null   str
 2   InteractionDate  3200 non-null   str
 3   Platform         2889 non-null   str
 4   InteractionType  3200 non-null   str
 5   Sentiment        2871 non-null   str
dtypes: str(6)
memory usage: 468.3 KB

In [5]:
#Checking the null values per column

df.isna().sum()

CustomerID           0
InteractionID        0
InteractionDate      0
Platform           311
InteractionType      0
Sentiment          329
dtype: int64

In [6]:
#Checking for global duplicates

df.duplicated().sum()

np.int64(180)

In [7]:
#Checking for duplicates in CustomerID

df["CustomerID"].duplicated().sum()

np.int64(1307)

In [8]:
#Checking for duplicates in InteractionID

df["InteractionID"].duplicated().sum()

np.int64(200)

In [9]:
#Showing all the rows for duplicates in InteractionID

df[df["InteractionID"].duplicated(keep=False)].sort_values("InteractionID")

,CustomerID,InteractionID,InteractionDate,Platform,InteractionType,Sentiment
2511,5db2e5ed-d30c-45db-b5f1-9db8008e178b,012dbb2a-3fbe-4b98-aa69-0304704db3c2,2024-05-26,NaN,Comment,Neutral
3176,5db2e5ed-d30c-45db-b5f1-9db8008e178b,012dbb2a-3fbe-4b98-aa69-0304704db3c2,2024-05-26,NaN,Comment,Neutral
1820,2ad7dcee-ed9c-4a7f-b631-377268bc623b,019fe9c3-83c6-49e4-b827-5ddd614c72df,2024-03-14,Instagram,Comment,Positive
3088,2ad7dcee-ed9c-4a7f-b631-377268bc623b,019fe9c3-83c6-49e4-b827-5ddd614c72df,2024-03-14,Instagram,Comment,Positive
374,11b046f0-b091-4bfb-b0f4-df58bfea039a,01f1c8c8-df21-4d75-adbb-feb6d4c84317,29/04/2024,Instagram,Like,Positive
...,...,...,...,...,...,...
3020,5edfab8a-fdac-4de4-92f0-2ca314b7fd59,fe6a907a-6c9a-45e8-bf5b-bad1a64227d9,2023-11-08,Facebook,Like,Positive
589,e76d99b7-f95c-416f-8d4e-5fe436a6414c,ff3e007a-70f9-49c7-bd8b-6bd8afa8f1cb,2023-09-02,Instagram,Share,NaN
3099,e76d99b7-f95c-416f-8d4e-5fe436a6414c,ff3e007a-70f9-49c7-bd8b-6bd8afa8f1cb,2023-09-02,Instagram,Share,NaN
420,648dac00-686c-41c0-8d59-3bee7d3bd390,ff459f1d-2c27-4696-a295-5a187d9c1f73,2024-01-24,Facebook,Like,Neutral
3066,648dac00-686c-41c0-8d59-3bee7d3bd390,ff459f1d-2c27-4696-a295-5a187d9c1f73,2024-01-24,Facebook,Like,Neutral

In [10]:
#Dropping global duplicates

df = df.drop_duplicates()

In [11]:
#Standardizing InteractionDate format

df["InteractionDate"] = pd.to_datetime(df["InteractionDate"], format="mixed", dayfirst=True, errors="coerce")

In [12]:
#Checking for possible null values in InteractionDate after standardization

df["InteractionDate"].isna().sum()

np.int64(0)

In [13]:
#Sorting dataset into InteractionDate and restarting the row number

df = df.sort_values("InteractionDate", ascending=True).reset_index(drop=True)

df

,CustomerID,InteractionID,InteractionDate,Platform,InteractionType,Sentiment
0,f9aed600-08f5-4583-b6d8-5ab32daaa213,dc68ea28-4ec2-456e-9af7-4dd76b372f32,2023-01-07,NaN,Share,Positive
1,d1c17e57-cbb9-4dc8-b638-ba2f1b1a8cef,54e79832-14c0-438e-a920-9cf042009df7,2023-01-07,Twitter,Like,Neutral
2,c3a5e86e-a74b-420e-b1e7-13bcbe6b71ac,8c1da393-7ea5-4405-b8c5-49953f75079a,2023-01-07,Instagram,Share,Very Positive
3,321acf6c-c401-4f7b-9835-bfb7cd5e48ff,973300c5-a0c7-4c13-a693-781ac8fe66ab,2023-01-07,Twitter,Share,Negative
4,76c1d696-0f1c-44b5-b749-8859545658eb,3ab03c80-fdaa-4dda-b769-4e8065ff1fff,2023-01-07,Facebook,Like,Positive
...,...,...,...,...,...,...
3015,e8a5fdb8-fcd9-450c-9635-e376266c8bcf,3d37f1e5-21f1-47dd-9cc4-b3a0a219e4a2,2024-12-06,Facebook,Share,Neutral
3016,8af27e3e-6225-43a1-b3b5-9a838531c97c,dd79b1f9-00ec-4e49-94f2-dacc6b5fdf19,2024-12-06,Instagram,Share,Positive
3017,9fc2bfa2-6dd0-4557-883b-18c88361a277,cbec4cf2-d9d2-48ef-8e32-87dc1f5cbc73,2024-12-06,Twitter,Comment,Neutral
3018,e12639d6-eeae-4436-a618-8e4b37aa16ac,00f5e1b2-82fb-425a-be54-50fcc2cc8c5e,2024-12-06,Facebook,Share,Positive
3019,404f9aca-5c0b-484f-a4ec-65ef1b401718,20fb41ec-2fe4-4ead-a810-4bb1519b6b9c,2024-12-06,Facebook,Share,Positive

In [14]:
#Checking to see if there are repeated Custoomer ID

df["CustomerID"].duplicated().sum()

np.int64(1127)

In [15]:
#Checking the number of unique CustomerID

df["CustomerID"].nunique()

1893

In [16]:
#Checking to see if there are repeated Interaction ID

df["InteractionID"].duplicated().sum()

np.int64(20)

In [17]:
#Creating a duplicates variable for the column InteractionID

duplicates = df[df["InteractionID"].duplicated(keep=False)]

duplicates

,CustomerID,InteractionID,InteractionDate,Platform,InteractionType,Sentiment
372,fd7e416c-1740-490d-b816-d909294eaa21,1d1c2f54-2b21-4004-a2ca-2983b01b0242,2023-07-17,Instagram,Share,Neutral
388,ef10b8a1-1014-4edf-a80e-207b7790e894,1966cdba-7e47-48b6-ae29-dd8fbead8527,2023-07-19,Twitter,Comment,Negative
389,ef10b8a1-1014-4edf-a80e-207b7790e894,1966cdba-7e47-48b6-ae29-dd8fbead8527,2023-07-19,Twitter,Comment,Very Negative
422,c0c0ce5a-4539-4013-abca-d0a3e41b4e2a,4639a6fd-3d89-4e1d-b783-f226eb92f14f,2023-07-23,Twitter,Comment,Negative
465,a44b6ca5-c73e-4f7a-919c-617931e33a29,13b59881-5aaf-4510-9dcf-4f9d116bf645,2023-07-28,Instagram,Like,Positive
496,3ea377e6-1156-457e-8b4e-71fa6663e6bf,9996e3b4-8270-4b04-a675-e00fe91dd835,2023-08-07,Facebook,Like,Positive
622,c3547dd4-61cc-495c-a7a2-b103bbae3835,85cb819c-9451-4028-9ddd-132c55260a68,2023-08-23,Twitter,Share,Positive
1035,a60e0cb6-7b43-44f2-956a-16caae372e9f,37ce93d2-27b5-478f-808c-3095cae7fae1,2023-10-22,Twitter,Comment,Positive
1037,a60e0cb6-7b43-44f2-956a-16caae372e9f,37ce93d2-27b5-478f-808c-3095cae7fae1,2023-10-22,Twitter,Comment,Very Negative
1042,c3547dd4-61cc-495c-a7a2-b103bbae3835,85cb819c-9451-4028-9ddd-132c55260a68,2023-10-23,Twitter,Share,Positive
1250,c0c0ce5a-4539-4013-abca-d0a3e41b4e2a,4639a6fd-3d89-4e1d-b783-f226eb92f14f,2023-11-24,Twitter,Comment,Negative
1296,ce2ece8f-91c3-420a-9d80-8b1f5051dc77,3a30bab5-53a0-4169-8244-419e2459dcd9,2023-11-30,Instagram,Share,Positive
1297,2ddc8052-fbbe-471c-a43e-54b81467423d,04391eb2-8391-44d8-9f45-29edcde96e5d,2023-11-30,Twitter,Share,Negative
1298,2ddc8052-fbbe-471c-a43e-54b81467423d,04391eb2-8391-44d8-9f45-29edcde96e5d,2023-11-30,Twitter,Share,Very Positive
1309,fd7e416c-1740-490d-b816-d909294eaa21,1d1c2f54-2b21-4004-a2ca-2983b01b0242,2023-11-30,Instagram,Share,Neutral
1323,3ea377e6-1156-457e-8b4e-71fa6663e6bf,9996e3b4-8270-4b04-a675-e00fe91dd835,2023-12-08,Facebook,Like,Positive
1375,b7b84b81-c61b-4f23-b3db-b18010484122,93d2d3e1-841e-4ece-91c1-3b1998a4cab8,2023-12-16,Twitter,Like,Neutral
1467,0831f0ad-bf6b-4023-b1bf-acea2388fcf3,a229e2d8-fd5d-44a1-805e-5281a52badf7,2023-12-27,Twitter,Comment,Negative
1480,0831f0ad-bf6b-4023-b1bf-acea2388fcf3,a229e2d8-fd5d-44a1-805e-5281a52badf7,2023-12-27,Twitter,Comment,Very Positive
1655,68afa4cc-e2d5-4150-b358-2e14e7508721,0942889b-a3a9-4039-b4b0-12fb8714c95f,2024-01-24,Twitter,Comment,Negative
1697,5659a8c6-0397-4396-b561-52ec1c8a760b,d7f6806b-f348-431e-9198-07f0685d8d8e,2024-01-28,Facebook,Share,Negative
1698,5659a8c6-0397-4396-b561-52ec1c8a760b,d7f6806b-f348-431e-9198-07f0685d8d8e,2024-01-28,Facebook,Share,Very Negative
1859,9b8179f4-f187-4cfd-b12a-0c182539f178,8570854d-62ce-4c74-8a2e-0b85ccc5774e,2024-02-22,Instagram,Comment,Neutral
1986,54c10762-4c2c-4b9a-a602-d0069520ab2b,1c28fcb7-81fc-462c-a0a3-785f00070cd7,2024-03-14,Facebook,Like,Positive
2028,11b046f0-b091-4bfb-b0f4-df58bfea039a,01f1c8c8-df21-4d75-adbb-feb6d4c84317,2024-03-20,Instagram,Like,Positive
2173,a56b8bed-1d7a-4cc2-abeb-d847aac0ff74,98cf7859-e4a9-465b-96fe-ed51a1f1aa92,2024-04-06,Facebook,Like,NaN
2179,a56b8bed-1d7a-4cc2-abeb-d847aac0ff74,98cf7859-e4a9-465b-96fe-ed51a1f1aa92,2024-04-06,Facebook,Like,Positive
2204,9b8179f4-f187-4cfd-b12a-0c182539f178,8570854d-62ce-4c74-8a2e-0b85ccc5774e,2024-04-15,Instagram,Comment,Neutral
2309,11b046f0-b091-4bfb-b0f4-df58bfea039a,01f1c8c8-df21-4d75-adbb-feb6d4c84317,2024-04-29,Instagram,Like,Positive
2321,e06f0e16-8e48-483b-b103-9f105b139ca8,071a2657-12a8-4216-9c64-baf9ab5c9420,2024-04-30,Twitter,Share,Neutral
2331,e06f0e16-8e48-483b-b103-9f105b139ca8,071a2657-12a8-4216-9c64-baf9ab5c9420,2024-04-30,Twitter,Share,Very Positive
2350,54c10762-4c2c-4b9a-a602-d0069520ab2b,1c28fcb7-81fc-462c-a0a3-785f00070cd7,2024-05-03,Facebook,Like,Positive
2398,b7b84b81-c61b-4f23-b3db-b18010484122,93d2d3e1-841e-4ece-91c1-3b1998a4cab8,2024-05-14,Twitter,Like,Neutral
2411,4d20c2b1-2f8a-4066-902c-bd068c2adccc,e5be1d7a-fdba-4e91-8674-577ac01cddf0,2024-05-16,NaN,Like,Very Negative
2414,4d20c2b1-2f8a-4066-902c-bd068c2adccc,e5be1d7a-fdba-4e91-8674-577ac01cddf0,2024-05-16,NaN,Like,Positive
2560,a44b6ca5-c73e-4f7a-919c-617931e33a29,13b59881-5aaf-4510-9dcf-4f9d116bf645,2024-06-04,Instagram,Like,Positive
2599,68afa4cc-e2d5-4150-b358-2e14e7508721,0942889b-a3a9-4039-b4b0-12fb8714c95f,2024-06-14,Twitter,Comment,Negative
2621,ce2ece8f-91c3-420a-9d80-8b1f5051dc77,3a30bab5-53a0-4169-8244-419e2459dcd9,2024-06-17,Instagram,Share,Positive
2697,5711d1af-71f2-4b99-a965-3ffdc39d32c8,1c2f510a-5ab5-4575-8f62-8ba8decf1302,2024-06-29,Twitter,Share,Negative
2707,5711d1af-71f2-4b99-a965-3ffdc39d32c8,1c2f510a-5ab5-4575-8f62-8ba8decf1302,2024-06-29,Twitter,Share,NaN

In [18]:
#Creating a variable to view difference in InteractionID per column

conflicts_InteractionID = duplicates.groupby("InteractionID").nunique()

conflicts_InteractionID

,CustomerID,InteractionDate,Platform,InteractionType,Sentiment
InteractionID,,,,,
01f1c8c8-df21-4d75-adbb-feb6d4c84317,1,2,1,1,1
04391eb2-8391-44d8-9f45-29edcde96e5d,1,1,1,1,2
071a2657-12a8-4216-9c64-baf9ab5c9420,1,1,1,1,2
0942889b-a3a9-4039-b4b0-12fb8714c95f,1,2,1,1,1
13b59881-5aaf-4510-9dcf-4f9d116bf645,1,2,1,1,1
1966cdba-7e47-48b6-ae29-dd8fbead8527,1,1,1,1,2
1c28fcb7-81fc-462c-a0a3-785f00070cd7,1,2,1,1,1
1c2f510a-5ab5-4575-8f62-8ba8decf1302,1,1,1,1,1
1d1c2f54-2b21-4004-a2ca-2983b01b0242,1,2,1,1,1
37ce93d2-27b5-478f-808c-3095cae7fae1,1,1,1,1,2
3a30bab5-53a0-4169-8244-419e2459dcd9,1,2,1,1,1
4639a6fd-3d89-4e1d-b783-f226eb92f14f,1,2,1,1,1
8570854d-62ce-4c74-8a2e-0b85ccc5774e,1,2,1,1,1
85cb819c-9451-4028-9ddd-132c55260a68,1,2,1,1,1
93d2d3e1-841e-4ece-91c1-3b1998a4cab8,1,2,1,1,1
98cf7859-e4a9-465b-96fe-ed51a1f1aa92,1,1,1,1,1
9996e3b4-8270-4b04-a675-e00fe91dd835,1,2,1,1,1
a229e2d8-fd5d-44a1-805e-5281a52badf7,1,1,1,1,2
d7f6806b-f348-431e-9198-07f0685d8d8e,1,1,1,1,2
e5be1d7a-fdba-4e91-8674-577ac01cddf0,1,1,0,1,2

In [19]:
conflicts_InteractionID = conflicts_InteractionID[(conflicts_InteractionID != 1).any(axis=1)]

conflicts_InteractionID

,CustomerID,InteractionDate,Platform,InteractionType,Sentiment
InteractionID,,,,,
01f1c8c8-df21-4d75-adbb-feb6d4c84317,1,2,1,1,1
04391eb2-8391-44d8-9f45-29edcde96e5d,1,1,1,1,2
071a2657-12a8-4216-9c64-baf9ab5c9420,1,1,1,1,2
0942889b-a3a9-4039-b4b0-12fb8714c95f,1,2,1,1,1
13b59881-5aaf-4510-9dcf-4f9d116bf645,1,2,1,1,1
1966cdba-7e47-48b6-ae29-dd8fbead8527,1,1,1,1,2
1c28fcb7-81fc-462c-a0a3-785f00070cd7,1,2,1,1,1
1d1c2f54-2b21-4004-a2ca-2983b01b0242,1,2,1,1,1
37ce93d2-27b5-478f-808c-3095cae7fae1,1,1,1,1,2
3a30bab5-53a0-4169-8244-419e2459dcd9,1,2,1,1,1
4639a6fd-3d89-4e1d-b783-f226eb92f14f,1,2,1,1,1
8570854d-62ce-4c74-8a2e-0b85ccc5774e,1,2,1,1,1
85cb819c-9451-4028-9ddd-132c55260a68,1,2,1,1,1
93d2d3e1-841e-4ece-91c1-3b1998a4cab8,1,2,1,1,1
9996e3b4-8270-4b04-a675-e00fe91dd835,1,2,1,1,1
a229e2d8-fd5d-44a1-805e-5281a52badf7,1,1,1,1,2
d7f6806b-f348-431e-9198-07f0685d8d8e,1,1,1,1,2
e5be1d7a-fdba-4e91-8674-577ac01cddf0,1,1,0,1,2

In [20]:
#Checking Unique value counts for Platform

df["Platform"].value_counts()

Platform
Instagram    921
Twitter      917
Facebook     891
Name: count, dtype: int64

In [21]:
#Checking Unique value counts for InteractionType

df["InteractionType"].value_counts()

InteractionType
Comment    1018
Share      1007
Like        995
Name: count, dtype: int64

In [22]:
#Checking Unique value counts for Sentiment

df["Sentiment"].value_counts()

Sentiment
Positive         905
Neutral          874
Negative         866
Very Negative     34
Very Positive     32
Name: count, dtype: int64

In [23]:
#Checking Unull values for Platform

df["Platform"].isna().sum()

#Recommend: Fill the na Platform to "Unspecified" and not mode to not skew the Platform distribution

np.int64(291)

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
#Filling the null values in Platform with "Unspecified" 

df["Platform"] = df["Platform"].fillna("Unspecified")

In [26]:
#Checking new Value counts of Platform

df["Platform"].value_counts()

Platform
Instagram      921
Twitter        917
Facebook       891
Unspecified    291
Name: count, dtype: int64

In [27]:
#Creating a variable for date conflicts

date_conflicts = conflicts_InteractionID[conflicts_InteractionID["InteractionDate"] > 1].index

In [28]:
#Finding the later date for each date conflict

later_date_rows = df[df["InteractionID"].isin(date_conflicts)].groupby("InteractionID")["InteractionDate"].idxmax()

In [29]:
#Dropping only the later date rows

df = df.drop(index=later_date_rows).sort_values("InteractionDate").reset_index(drop=True)

In [30]:
#Refresh conflicts_InteractionID

duplicates = df[df["InteractionID"].duplicated(keep=False)]

conflicts_InteractionID = duplicates.groupby("InteractionID").nunique()

conflicts_InteractionID = conflicts_InteractionID[(conflicts_InteractionID != 1).any(axis=1)]

conflicts_InteractionID

,CustomerID,InteractionDate,Platform,InteractionType,Sentiment
InteractionID,,,,,
04391eb2-8391-44d8-9f45-29edcde96e5d,1,1,1,1,2
071a2657-12a8-4216-9c64-baf9ab5c9420,1,1,1,1,2
1966cdba-7e47-48b6-ae29-dd8fbead8527,1,1,1,1,2
37ce93d2-27b5-478f-808c-3095cae7fae1,1,1,1,1,2
a229e2d8-fd5d-44a1-805e-5281a52badf7,1,1,1,1,2
d7f6806b-f348-431e-9198-07f0685d8d8e,1,1,1,1,2
e5be1d7a-fdba-4e91-8674-577ac01cddf0,1,1,1,1,2

In [31]:
#Checking actual values of Sentiment from conflicts

df[df["InteractionID"].isin(conflicts_InteractionID.index)].sort_values("InteractionID")

#Analysis: Unable to create a justifiable way to choose which sentiment to retain and to drop, Flagging these rows for conflicting values
#Action: Will retain the data and treat this as two separate interaction from a customer despite having the same InteractionID

,CustomerID,InteractionID,InteractionDate,Platform,InteractionType,Sentiment
1303,2ddc8052-fbbe-471c-a43e-54b81467423d,04391eb2-8391-44d8-9f45-29edcde96e5d,2023-11-30,Twitter,Share,Very Positive
1304,2ddc8052-fbbe-471c-a43e-54b81467423d,04391eb2-8391-44d8-9f45-29edcde96e5d,2023-11-30,Twitter,Share,Negative
2314,e06f0e16-8e48-483b-b103-9f105b139ca8,071a2657-12a8-4216-9c64-baf9ab5c9420,2024-04-30,Twitter,Share,Very Positive
2323,e06f0e16-8e48-483b-b103-9f105b139ca8,071a2657-12a8-4216-9c64-baf9ab5c9420,2024-04-30,Twitter,Share,Neutral
384,ef10b8a1-1014-4edf-a80e-207b7790e894,1966cdba-7e47-48b6-ae29-dd8fbead8527,2023-07-19,Twitter,Comment,Very Negative
385,ef10b8a1-1014-4edf-a80e-207b7790e894,1966cdba-7e47-48b6-ae29-dd8fbead8527,2023-07-19,Twitter,Comment,Negative
1029,a60e0cb6-7b43-44f2-956a-16caae372e9f,37ce93d2-27b5-478f-808c-3095cae7fae1,2023-10-22,Twitter,Comment,Very Negative
1031,a60e0cb6-7b43-44f2-956a-16caae372e9f,37ce93d2-27b5-478f-808c-3095cae7fae1,2023-10-22,Twitter,Comment,Positive
1464,0831f0ad-bf6b-4023-b1bf-acea2388fcf3,a229e2d8-fd5d-44a1-805e-5281a52badf7,2023-12-27,Twitter,Comment,Very Positive
1477,0831f0ad-bf6b-4023-b1bf-acea2388fcf3,a229e2d8-fd5d-44a1-805e-5281a52badf7,2023-12-27,Twitter,Comment,Negative
1686,5659a8c6-0397-4396-b561-52ec1c8a760b,d7f6806b-f348-431e-9198-07f0685d8d8e,2024-01-28,Facebook,Share,Negative
1687,5659a8c6-0397-4396-b561-52ec1c8a760b,d7f6806b-f348-431e-9198-07f0685d8d8e,2024-01-28,Facebook,Share,Very Negative
2403,4d20c2b1-2f8a-4066-902c-bd068c2adccc,e5be1d7a-fdba-4e91-8674-577ac01cddf0,2024-05-16,Unspecified,Like,Positive
2407,4d20c2b1-2f8a-4066-902c-bd068c2adccc,e5be1d7a-fdba-4e91-8674-577ac01cddf0,2024-05-16,Unspecified,Like,Very Negative

In [32]:
#Checking for null values in Sentiment

df["Sentiment"].isna().sum()

#Analysis: 10% of data will be imputed, it will skew the EDA. 
#Recommend: Instead of imputing mode or dropping rows, fill null values with Unknown

np.int64(309)

In [33]:
#Filling the null values with "Unknown"

df["Sentiment"] = df["Sentiment"].fillna("Unknown")

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3009 entries, 0 to 3008
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       3009 non-null   str
 1   InteractionID    3009 non-null   str
 2   InteractionDate  3009 non-null   datetime64[us]
 3   Platform         3009 non-null   str
 4   InteractionType  3009 non-null   str
 5   Sentiment        3009 non-null   str
dtypes: datetime64[us](1), str(5)
memory usage: 417.0 KB

In [35]:
df.sample(25)

,CustomerID,InteractionID,InteractionDate,Platform,InteractionType,Sentiment
2138,2fb831c7-4ce9-435b-959d-3f69e179a6bf,1334b10c-320d-4cd2-bc0e-f2434b6783ed,2024-04-03,Twitter,Share,Negative
434,e8a5fdb8-fcd9-450c-9635-e376266c8bcf,188baa55-d207-41ab-9c46-59d2a1b28783,2023-07-25,Instagram,Like,Neutral
869,a0d6d267-5374-437e-9d14-2f781c3170c2,45f3db62-274e-42ef-80e9-3afeef7deee6,2023-09-28,Twitter,Comment,Unknown
2680,249a52ef-4f20-4035-ade0-4855537d75a2,6fe737c6-c6d2-4b9e-b603-661bd47704c4,2024-06-28,Instagram,Comment,Negative
1316,d2c44a3f-8094-4a89-aa38-1c49a82f41ae,3a240a8a-0f23-4f77-b025-a465fbfd5a96,2023-12-08,Facebook,Comment,Neutral
2014,1e9e7dcb-e612-46d3-bae6-0c2f47fa0220,e9cf9df4-6f59-4e47-83c0-ec77f1fc34fb,2024-03-18,Twitter,Share,Positive
915,9bd04ab1-225d-48d3-a9f9-f2338a40a439,05bb4fe9-f964-4a11-8ad3-70a9ce70289a,2023-10-09,Facebook,Like,Positive
2024,11b046f0-b091-4bfb-b0f4-df58bfea039a,01f1c8c8-df21-4d75-adbb-feb6d4c84317,2024-03-20,Instagram,Like,Positive
2307,d74439c1-90e1-4a46-951e-89fe6e092b9f,fd08c79b-8cd1-4d2e-9104-57442568e9c5,2024-04-29,Instagram,Comment,Negative
2574,752d0d0f-c234-44cb-b36d-8808b640faae,88979bf0-b8c5-4b98-9049-61a2952cd408,2024-06-13,Facebook,Like,Negative
2416,03d5404d-aa72-4d9d-b49b-562036780b34,2fe3992b-9f25-46ae-b18c-83059614764d,2024-05-18,Facebook,Comment,Positive
2524,48c379ee-e82e-494c-ab4b-0d813a8b9884,017254b1-c9fb-40a7-861c-69b67d29243c,2024-05-31,Instagram,Share,Negative
896,5dcc04f0-2300-4707-b737-82abb839b428,24bc4157-e0e9-47d4-a415-1bf0f63c4a42,2023-10-07,Facebook,Share,Positive
1425,9556b64c-756a-4825-8c23-26a54a672a01,dbd90d64-f97b-4928-8f0b-b111ce4f1c66,2023-12-22,Unspecified,Like,Unknown
2886,c3f22991-8910-4823-86e4-8637520d3952,3922576f-cdc9-40af-b1a3-22baed6e8a8e,2024-10-05,Twitter,Comment,Positive
2175,3cdced98-055c-4037-a0a5-5f01cbc707b9,2a67a671-3507-4247-b240-786dddf33487,2024-04-06,Facebook,Comment,Positive
2823,af22c4bc-8b3d-4261-9920-fddb8b83607b,72036e42-66f1-4add-9919-45244e50348d,2024-09-02,Facebook,Comment,Negative
2960,a9af986b-d677-421a-81df-3d289ce9e38f,97cc0320-3548-45dd-8ece-a967f01dd856,2024-12-01,Facebook,Like,Neutral
2532,404f9aca-5c0b-484f-a4ec-65ef1b401718,bd50871e-235e-44f8-aaa8-faafaf580b4f,2024-06-02,Instagram,Like,Unknown
2017,e2114d58-4f01-483d-84fe-cd9601cc8be9,b722f2f9-e529-4e47-b68c-9f44127284ab,2024-03-19,Twitter,Like,Neutral
2727,70a64f68-8300-40b7-9d3e-932bf73ba7e1,dc38f6e1-0737-4583-a471-8f614ea836dc,2024-07-03,Instagram,Like,Positive
604,d18cda69-56ba-45a8-b3fe-ff52f040377a,8371e3a6-cbd5-4a07-9a7f-b334d046644e,2023-08-20,Instagram,Share,Unknown
2542,509c0596-50f8-4e68-8204-ddf396e67862,ebff598f-bcaa-4e12-a9ac-1699b0693411,2024-06-03,Instagram,Comment,Neutral
284,37fe7939-62de-48d6-bd1a-80ec3bb670aa,d28f7c6b-3a7f-4702-86ac-09c2c5ae6d23,2023-07-06,Twitter,Share,Positive
2899,08995799-8d0f-40d6-986b-452074709b5f,eef7b68c-25ad-40a4-b8c4-c7a67470b509,2024-10-06,Facebook,Comment,Negative

In [36]:
#Saving the cleaned file 

df.to_csv("Social Media Interactions Cleaned.csv" , index=False)

In [37]:
print("\n\n=== Social Media Interactions ===")

print("\nPlatform:")
print(df["Platform"].value_counts())

print("\nInteraction Type:")
print(df["InteractionType"].value_counts())

print("\nSentiment:")
print(df["Sentiment"].value_counts())

=== Social Media Interactions ===

Platform:
Platform
Instagram      916
Twitter        913
Facebook       889
Unspecified    291
Name: count, dtype: int64

Interaction Type:
InteractionType
Comment    1015
Share      1004
Like        990
Name: count, dtype: int64

Sentiment:
Sentiment
Positive         899
Neutral          871
Negative         864
Unknown          309
Very Negative     34
Very Positive     32
Name: count, dtype: int64